# Generated by Django 4.2.2 on 2023-09-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadFile', '0002_uploadeddocument_delete_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploadedFile',
            fields=[
                ('fileId', models.AutoField(primary_key=True, serialize=False)),
                ('fileName', models.CharField(max_length=100)),
                ('fileExt', models.CharField(max_length=20)),
                ('short_url', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='uploadedDocument',
        ),
    ]
