# Generated by Django 5.0 on 2024-02-14 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadFile', '0003_uploadedfile_delete_uploadeddocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='url',
            field=models.CharField(default=12, max_length=255),
            preserve_default=False,
        ),
    ]
