# Generated by Django 5.0 on 2024-03-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadFile', '0004_uploadedfile_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(default=None, max_length=200, null=True, upload_to='image'),
        ),
    ]
